language: node_js
node_js:
  - '0.9'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lingon-plugin' ]; then cd .. && eval "mv $currentfolder generator-lingon-plugin" && cd generator-lingon-plugin; fi
